version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - redis
  worker:
    build: .
    command: celery -A app.worker.celery worker --loglevel=INFO
    env_file: .env
    depends_on:
      - redis
  beat:
    build: .
    command: celery -A app.worker.celery beat --loglevel=INFO --schedule /tmp/celerybeat-schedule
    env_file: .env
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
